WhiteLagoon/Controllers/VillaController.cs
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Web.ViewModels;

namespace WhiteLagoon.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork context, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var villas = _unitOfWork.Villa.GetAll();
            return View(villas);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("Name", "The name cannot exactly match the name");
            }
            if (ModelState.IsValid)
            {
                if (obj.Image != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villa");
                    using (FileStream fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
                    {
                        obj.Image.CopyTo(fileStream);
                        obj.ImageUrl = @"\images\Villa\" + fileName;
                    }
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }
                _unitOfWork.Villa.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa has been created successfully";

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public IActionResult Update(int villaId)
        {
            Villa? obj = _unitOfWork.Villa.Get(u => u.ID == villaId);
            if (obj == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Update(Villa obj)
        {

            if (ModelState.IsValid && obj.ID > 0)
            {
                if (obj.Image != null)
                {
                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImageUrl = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImageUrl))
                        {
                            System.IO.File.Delete(oldImageUrl);
                        }

                    }
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villa");
                    using (FileStream fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
                    {
                        obj.Image.CopyTo(fileStream);
                        obj.ImageUrl = @"\images\Villa\" + fileName;
                    }
                }
                _unitOfWork.Villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa has been updated successfully";

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public IActionResult Delete(int villaId)
        {
            Villa? obj = _unitOfWork.Villa.Get(u => u.ID == villaId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
            Villa? objFromDb = _unitOfWork.Villa.Get(u => u.ID == obj.ID);
            if (objFromDb is not null)
            {
                if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
                {
                    var oldImageUrl = Path.Combine(_webHostEnvironment.WebRootPath, objFromDb.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImageUrl))
                    {
                        System.IO.File.Delete(oldImageUrl);
                    }

                }
                _unitOfWork.Villa.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Villa has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["success"] = "Villa could not be deleted successfully";

            return View();
        }
    }
}

WhiteLagoon/Views/Villa/Create.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4 border">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                    <input asp-for="Image" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Sqm" class="form-control border shadow" />
                    <label asp-for="Sqm" class="ms-2"></label>
                    <span asp-validation-for="Sqm" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100"> <i class="bi bi-plus-circle-fill"></i>
                            Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <button asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100"><i
                                class="bi bi-x-circle-fill"></i> Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon/Views/Villa/Delete.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4 border">
        <form method="post" class="row">
            <input asp-for="ID" hidden />
            <div class="col-10">

                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly"></div> *@
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Name" disabled class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Description" disabled class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Price" disabled class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="ImageUrl" disabled class="form-control border shadow" />
                        <label asp-for="Image" class="ms-2"></label>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Sqm" disabled class="form-control border shadow" />
                        <label asp-for="Sqm" class="ms-2"></label>
                        <span asp-validation-for="Sqm" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Occupancy" disabled class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-danger w-100"><i class="bi bi-trash-fill"> </i>Delete</button>
                        </div>
                        <div class="col-6 col-md-3">
                            <button asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle-fill"></i> Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" style="border-radius: 5px; border: 1px solid #bbb9b9" width="100%" />
            </div>
        </form>
    </div>
</div>

WhiteLagoon/Views/Villa/Index.cshtml
@model IEnumerable<Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle-fill"></i> Create new Villa
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Sqm</th>
                    <th>Occupancy</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.Price</td>
                        <td>@obj.Sqm</td>
                        <td>@obj.Occupancy</td>
                        <td>
                            <div class="w-75 btn-group" role="group">

                                <a asp-action="Update" asp-route-villaId="@obj.ID" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i>Edit
                                </a>
                                <a asp-action="Delete" asp-route-villaId="@obj.ID" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i>Remove
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WhiteLagoon/Views/Villa/Update.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4 border">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="ID" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly"></div> *@
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                        <input asp-for="Image" class="form-control border shadow" />
                        <label asp-for="Image" class="ms-2"></label>
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Sqm" class="form-control border shadow" />
                        <label asp-for="Sqm" class="ms-2"></label>
                        <span asp-validation-for="Sqm" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100"><i class="bi bi-check-circle"> </i>Update</button>
                        </div>
                        <div class="col-6 col-md-3">
                            <button asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle-fill"></i> Cancel
                            </button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" style="border-radius: 5px; border: 1px solid #bbb9b9" width="100%" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}